spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.banco.ddd: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

server:
  error:
    include-message: never
    include-stacktrace: never
